services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Другой порт, чтобы не конфликтовать с основным приложением
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 5

  app:
    build: ../../app  # Собираем из папки app
    ports:
      - "8001:8000"  # Другой порт для тестового приложения
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/app_db
      # Переменные окружения для нагрузочного тестирования
      FLASK_ENV: production
      LOG_LEVEL: WARNING  # Уменьшаем логирование для тестов
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../../app:/app
    restart: on-failure:3
    command: python init_app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    

volumes:
  postgres_data:
