services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 5

  app:
    build: ../app
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/app_db
      PYTHONUNBUFFERED: 1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../app:/app
    restart: on-failure:3
    command: python init_app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 2s
      retries: 5

  acceptance-tests:
    build: .
    depends_on:
      app:
        condition: service_healthy
    environment:
      PYTHONUNBUFFERED: 1

volumes:
  postgres_data: 